#!/usr/bin/env python3

from sys import stdout  # standard output
from time import sleep  # sleep for x seconds


def timer(minutes, message):
    seconds = 60
    for m in range(minutes, 0, -1):
        for s in range(seconds, 0, -1):
            time = str(f'{m - 1:02}') + ':' + str(f'{s - 1:02} ') + message
            stdout.write('\r' + time)
            sleep(1)
            if seconds == 0:
                seconds = 60
                break


while (True):
    timer(25, '🍅 Work time!')
    timer(5, '🍵 Break time, grab some tea')
