#!/usr/bin/env python3

from sys import stdout  # standard output
from time import sleep  # sleep for x seconds


def timer(minutes):
    seconds = 60
    for m in range(minutes, 0, -1):
        for s in range(seconds, 0, -1):
            stdout.write('\r' + str(f'{m - 1:02}') + ':' + str(f'{s - 1:02}'))
            sleep(1)
            if seconds == 0:
                seconds = 60
                break


while (True):
    timer(25)
    timer(5)
